vdev: remove useless VHD_VERIFY(stat) check
AFAIK 'stat' is the function, hence check for stat no being
NULL doesn't make sence. Author likely meant something else here.

This also fixes the warning:

In file included from virtio/virtio_spec.h:10,
                 from virtio/virt_queue.h:8,
                 from vdev.h:6,
                 from vdev.c:13:
vdev.c: In function ‘vhd_vdev_get_queue_stat’:
./platform.h:90:13: error: the address of ‘stat’ will always evaluate as ‘true’ [-Werror=address]
   90 |         if (!(cond)) {                                    \
      |             ^
vdev.c:1762:1: note: in expansion of macro ‘VHD_VERIFY’
 1762 | VHD_VERIFY(stat);

Signed-off-by: Andrey Ryabinin <arbn@yandex-team.ru>