memmap.c: suppress gcc warning
Older gcc says:

  ../subprojects/yc-libvhost-server/memmap.c:415:5: error: missing
      initializer for field 'num' of 'struct vhd_memory_map'
      [-Werror=missing-field-initializers]
    415 |     };
        |     ^
  ../subprojects/yc-libvhost-server/memmap.c:101:14: note: 'num'
      declared here
    101 |     unsigned num;
        |              ^~~

version:

    gcc --version
    gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

Let's just satisfy it.

Signed-off-by: Vladimir Sementsov-Ogievskiy <vsementsov@yandex-team.ru>