include/vhost/types.h: add missing include <strint.h>
Fixes:
In file included from virtio/virt_queue.h:5,
                 from vdev.h:6,
                 from vdev.c:13:
./include/vhost/types.h:23:5: error: unknown type name ‘uint64_t’
   23 |     uint64_t request_total;

Signed-off-by: Andrey Ryabinin <arbn@yandex-team.ru>